#ifndef __STRING_DEF_H__
#define __STRING_DEF_H__

#define STR_ENGLISH		(0)
#define STR_ASK_SOUND		(1)
#define STR_YES		(2)
#define STR_NO		(3)
#define STR_LOADING		(4)
#define STR_ASK_EXIT		(5)
#define STR_ASK_BACKTOMM		(6)
#define STR_ASK_RESET		(7)
#define STR_PRESS_ANY_KEY		(8)
#define STR_HIGHSCORE		(9)
#define STR_GAMEOVER		(10)
#define STR_VICTORY		(11)
#define STR_ABOUT		(12)
#define STR_NEWGAME		(13)
#define STR_LOADGAME		(14)
#define STR_LEADERBOARD		(15)
#define STR_QUIT		(16)
#define STR_OPTION		(17)
#define STR_RESETGAME		(18)
#define STR_SOUND		(19)
#define STR_SOUND_ON		(20)
#define STR_SOUND_OFF		(21)
#define STR_MAINMENU		(22)
#define STR_ENDGAME		(23)
#define STR_HELP		(24)
#define STR_LANGUAGE		(25)
#define STR_PLAY		(26)
#define STR_RESUME		(27)
#define STR_ABOUT_0		(28)
#define STR_HELP_0		(29)
#define STR_PRESS_ANY_KEY_OR_TOUCH		(30)
#define STR_ALL		(31)
#define STR_TOTAL		(32)

#endif
